export const routeTypes = {
  INBOUND: 0,
  OUTBOUND: 1,
  ENROUTE: 2,
  0: 'inbound',
  1: 'outbound',
  2: 'enroute',
}

export const airplanes = [
  {
    id: 0,
    ceiling: 37,
    name: 'Boeing 737',
    shortName: 'B737',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [0, 1, 2, 3, 4, 7, 10, 11, 12, 13, 14, 22, 23],
  },
  {
    id: 1,
    name: 'Boeing 747',
    shortName: 'B747',
    topSpeed: 330,
    landingSpeed: 145,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 180,
    turningRate: [2, 3, 4],
    ceiling: 41,
    operators: [0, 1, 2, 3, 6, 8, 14, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 2,
    name: 'Boeing 757',
    shortName: 'B757',
    topSpeed: 330,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    turningRate: [3, 4, 5],
    ceiling: 42,
    operators: [0, 1, 2, 3, 5, 7, 16, 17]
  },
  {
    id: 3,
    name: 'Boeing 767',
    shortName: 'B767',
    topSpeed: 330,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    turningRate: [2, 3, 4],
    ceiling: 43,
    operators: [1, 3, 5, 6, 7, 12, 16],
  },
  {
    id: 4,
    name: 'Boeing 777',
    shortName: 'B777',
    topSpeed: 330,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    turningRate: [3, 3, 4],
    ceiling: 43,
    operators: [0, 1, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 18, 19, 20, 23],
  },
  {
    id: 5,
    name: 'Airbus A380',
    shortName: 'A380',
    topSpeed: 330,
    landingSpeed: 150,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    turningRate: [2, 3, 3],
    ceiling: 43,
    operators: [6, 9, 10, 15, 20]
  },
  {
    id: 6,
    name: 'Airbus A330',
    shortName: 'A330',
    ceiling: 39,
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [0, 1, 3, 5, 8, 9, 11, 14, 18, 19, 20, 22, 23],
  },
  {
    id: 7,
    ceiling: 39,
    name: 'Boeing 787 Dreamliner',
    shortName: 'B787',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [0, 3, 5, 6, 10, 11, 12, 19, 22, 23],
  },
  {
    id: 8,
    ceiling: 37,
    name: 'Airbus A319',
    shortName: 'A319',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [1, 5, 6, 8, 10, 11, 14, 19, 22],
  },
  {
    id: 9,
    ceiling: 37,
    name: 'Airbus A320',
    shortName: 'A320',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [1, 2, 3, 5, 6, 8, 9, 10, 11, 12, 14, 19, 20, 22, 23],
  },
  {
    id: 10,
    ceiling: 37,
    name: 'Airbus A321',
    shortName: 'A321',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [1, 2, 3, 5, 6, 8, 9, 10, 11, 12, 14, 19, 20, 23],
  },
  {
    id: 11,
    ceiling: 41,
    name: 'Airbus A350',
    shortName: 'A350',
    topSpeed: 320,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 160,
    turningRate: [2, 3, 5],
    operators: [1, 8, 10, 14, 18, 19, 22],
  },
  {
    id: 12,
    ceiling: 35,
    name: 'Boeing 717',
    shortName: 'B717',
    topSpeed: 300,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [1],
  },
  {
    id: 13,
    ceiling: 35,
    name: 'McDonell Douglas MD-88',
    shortName: 'MD-88',
    topSpeed: 300,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [1],
  },
  {
    id: 14,
    ceiling: 35,
    name: 'McDonell Douglas MD-90',
    shortName: 'MD-90',
    topSpeed: 300,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [1],
  },
  {
    id: 15,
    ceiling: 38,
    name: 'Embraer 190',
    shortName: 'E190',
    topSpeed: 310,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [2, 5, 10],
  },
  {
    id: 16,
    ceiling: 35,
    name: 'McDonell Douglas MD-82',
    shortName: 'MD-82',
    topSpeed: 300,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [5],
  },
  {
    id: 17,
    ceiling: 35,
    name: 'McDonell Douglas MD-83',
    shortName: 'MD-83',
    topSpeed: 300,
    landingSpeed: 140,
    climbSpeed: 1,
    decendSpeed: 1,
    accelerationSpeed: 1,
    deAccelerationSpeed: 1,
    minSpeed: 150,
    turningRate: [2, 3, 5],
    operators: [5],
  },

];

export const operators = [
  {
    id: 0,
    name: 'KLM',
    shortName: 'KLM',
    callsign: 'KLM',
    color: '#00a1e4'
  }, {
    id: 1,
    name: 'Delta Airlines',
    callsign: 'DLT',
    shortName: 'Delta',
    color: '#003a70'
  }, {
    id: 2,
    name: 'JetBlue',
    callsign: 'JBU',
    shortName: 'JetBlue',
    color: '#003876'
  }, {
    id: 3,
    name: 'United Airlines',
    callsign: 'UAL',
    shortName: 'United',
    color: '#005DAA'
  },
  {
    id: 4,
    name: 'Southwest Airlines',
    callsign: 'SWA',
    shortName: 'Southwest',
    color: '#304cb2',
  },
  {
    id: 5,
    name: 'American Airlines',
    callsign: 'AAL',
    shortName: 'American',
    color: '#d41525'
  },
  {
    id: 6,
    name: 'British Airways',
    callsign: 'BAW',
    shortName: 'Speedbird',
    color: '#2a5c9a',
  },
  {
    id: 7,
    name: 'Continental Airlines',
    callsign: 'COA',
    shortName: 'Continental',
    color: '#0060aa'
  },
  {
    id: 8,
    name: 'Lufthansa',
    callsign: 'DLH',
    shortName: 'Lufthansa',
    color: '#00225e'
  },
  {
    id: 9,
    name: 'Air France',
    callsign: 'AFR',
    shortName: 'Air France',
    color: '#002157',
  },
  {
    id: 10,
    name: 'China Southern Airlines',
    callsign: 'CSN',
    shortName: 'China Southern',
    color: '#008dd2'
  },
  {
    id: 11,
    name: 'China Eastern Airlines',
    callsign: 'CES',
    shortName: 'China Eastern',
    color: '#e31614'
  },
  {
    id: 12,
    name: 'All Nippon Airways',
    callsign: 'ANA',
    shortName: 'All Nippon',
    color: '#083191'
  },
  {
    id: 13,
    name: 'Ryanair',
    callsign: 'RYR',
    shortName: 'Ryanair',
    color: '#0027b5',
  },
  {
    id: 14,
    name: 'Turkish Airlines',
    callsign: 'THY',
    shortName: 'Turkish',
    color: '#ee2e24'
  },
  {
    id: 15,
    name: 'Emirates',
    callsign: 'UAE',
    shortName: 'Emirates',
    color: '#d8131b'
  },
  {
    id: 16,
    name: 'FedEx Express',
    callsign: 'FDX',
    shortName: 'Fedex',
    color: '#2a007c'
  },
  {
    id: 17,
    name: 'UPS Airlines',
    callsign: 'UPS',
    shortName: 'UPS',
    color: '#fab903',
  },
  {
    id: 18,
    name: 'Cathay Pacific',
    callsign: 'CPA',
    shortName: 'Cathay',
    color: '#006b6e'
  },
  {
    id: 19,
    name: 'Qatar Airways',
    callsign: 'QTR',
    shortName: 'Qatari',
    color: '#5c0632',
  },
  {
    id: 20,
    name: 'Korean Air',
    callsign: 'KAL',
    shortName: 'Korean Air',
    color: '#154d9e'
  },
  {
    id: 21,
    name: 'Cargolux',
    callsign: 'CLX',
    shortName: 'Cargolux',
    color: '#d40000'
  },
  {
    id: 22,
    name: 'Air China',
    callsign: 'CCA',
    shortName: 'Air China',
    color: '#ee151f'
  },

  {
    id: 23,
    name: 'Egyptair',
    callsign: 'MSR',
    shortName: 'Egyptair',
    color: '#00265d',
  }
];

export const airplanesById = Object.assign({}, ...airplanes.map(x => ({ [x.id]: x })));

export const operatorsById = Object.assign({}, ...operators.map(x => ({ [x.id]: x })));

