export default {
  headingInitVariation: 10,
  globalSpeed: 1,
  baseAirplaneSpeed: 0.0015,
  updateInterval: 300,
  headingIndicatorLineLen: 20,
  pathCounterUpdateEvery: 20,
  maxPathLen: 10,
  rwyLenScale: 0.0014,
  ilsSlopeSteepness: 37.5,
  threeMileRuleDistance: 15,
  climbSpeed: 18,
  decendSpeed: 22,
  accelerationSpeed: 1.6,
  deAccelerationSpeed: 1.2,
}