export default {
  headingInitVariation: 10,
  globalSpeed: 1,
  baseAirplaneSpeed: 0.0015,
  updateInterval: 300,
  updateTimelapseInterval: 20,
  headingIndicatorLineLen: 20,
  pathCounterUpdateEvery: 25,
  updateWeatherEvery: 200,
  maxPathLen: 10,
  rwyLenScale: 0.0014,
  ilsSlopeSteepness: 37.5,
  threeMileRuleDistance: 15,
  oneMileRuleDistance: 5,
  runwayParrelelSepRuleDistance: 1,
  climbSpeed: 14,
  descendSpeed: 18,
  accelerationSpeed: 1.6,
  deAccelerationSpeed: 1.2,
  turnRate: 0.3,
  flyStraightAfterTakeoffUntilHeight: 2000,
  airplaneTextDistance: 7,
  width: 1280,
  height: 720,
  controlAreaRadius: 200,
  inboundPatternEntryDistance: 100,
  maxTrafficPatternSpeed: 210,
  maxTouchAndGos: 9,
  zoomSpeed: .002,
  minZoom: 1,
  maxZoom: 6,
  windSpdChange: 3,
  windDirChange: 5,
  windSpdMin: 1,
  windSpdMax: 30,
  roughWindSpd: 10,
  extremeWindSpd: 20,
  windRandomChangeOfLoweringWhenRoughWindSpd: 0.05,
  likelyNessOfGoAroundDueWindSpd: 0.01,
  likelyNessOfGoAroundDueWindHhdg: 0.01,
  likelyNessOfGoAround: 0.01,
  description: 'ATC Manager 2 is a web based air traffic control game. ' 
   + 'Manage airspace of busy airports like Schiphol or Heathrow in a ' 
   + 'realistic simulator.',
  url: 'https://esstudio.site/atc-manager-2/#/',
  urlRaw: 'https://esstudio.site/atc-manager-2/',
  feedUrl: 'https://esstudio.site/atc-manager-2-feed.xml',
  publicVapidKey: 'BABOUEnL-6mHr6Sf60UnNQS0cWHPmFXNmwTV2jHIoHAwdqOLJzGnbs-qr_BBxx1ePVozJa8qQzQamriCs5uU9EY',
  subscriptionURL: 'https://ess-server.herokuapp.com/api/notifications/atc%20manager%202/subscribe',
  textRotation: 0,
  groundPixelPadding: 100,
  version: 5
};